name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Node.js image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app-image:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app-image:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app-image:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app-image:${{ github.sha }}

    - name: Replace node-app-image name in node-app.yaml #
      run: sed -i 's|node-app-image|${{ secrets.DOCKERHUB_USERNAME }}/node-app-image:latest|g' node-app.yaml

    - name: Start Minikube
      run: |
        minikube start --driver=docker
        minikube kubectl -- get pods --all-namespaces

    - name: Apply Kubernetes ConfigMap
      run: kubectl apply -f mongo-config.yaml

    - name: Apply Kubernetes Secret
      run: kubectl apply -f mongo-secret.yaml

    - name: Apply MongoDB Deployment and Service
      run: kubectl apply -f mongo-app.yaml

    - name: Apply Node.js Deployment and Service
      run: kubectl apply -f node-app.yaml