name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start Minikube
      run: |
        minikube start --driver=docker
        minikube kubectl -- get pods --all-namespaces

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: asad199/docker-k8-learning-api
        tags: ${{ github.sha }}, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Replace node-app-image name in node-app.yaml #
      run: sed -i 's|node-app-image|${{ secrets.DOCKERHUB_USERNAME }}/docker-k8-learning-api:latest|g' node-app.yaml

    - name: Apply Kubernetes ConfigMap
      run: kubectl apply -f mongo-config.yaml

    - name: Apply Kubernetes Secret
      run: kubectl apply -f mongo-secret.yaml

    - name: Apply MongoDB Deployment and Service
      run: kubectl apply -f mongo-app.yaml

    - name: Apply Node.js Deployment and Service
      run: kubectl apply -f node-app.yaml